/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as StudyPlannerRouteImport } from './routes/study-planner'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SmartHomeRouteImport } from './routes/smart-home'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlannerRoute = StudyPlannerRouteImport.update({
  id: '/study-planner',
  path: '/study-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeRoute = SmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/friends': typeof FriendsRoute
  '/reader': typeof ReaderRoute
  '/routine': typeof RoutineRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/smart-home': typeof SmartHomeRoute
  '/study': typeof StudyRoute
  '/study-planner': typeof StudyPlannerRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/friends': typeof FriendsRoute
  '/reader': typeof ReaderRoute
  '/routine': typeof RoutineRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/smart-home': typeof SmartHomeRoute
  '/study': typeof StudyRoute
  '/study-planner': typeof StudyPlannerRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/friends': typeof FriendsRoute
  '/reader': typeof ReaderRoute
  '/routine': typeof RoutineRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/smart-home': typeof SmartHomeRoute
  '/study': typeof StudyRoute
  '/study-planner': typeof StudyPlannerRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/chat'
    | '/files'
    | '/friends'
    | '/reader'
    | '/routine'
    | '/security'
    | '/settings'
    | '/smart-home'
    | '/study'
    | '/study-planner'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/chat'
    | '/files'
    | '/friends'
    | '/reader'
    | '/routine'
    | '/security'
    | '/settings'
    | '/smart-home'
    | '/study'
    | '/study-planner'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/chat'
    | '/files'
    | '/friends'
    | '/reader'
    | '/routine'
    | '/security'
    | '/settings'
    | '/smart-home'
    | '/study'
    | '/study-planner'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  ChatRoute: typeof ChatRoute
  FilesRoute: typeof FilesRoute
  FriendsRoute: typeof FriendsRoute
  ReaderRoute: typeof ReaderRoute
  RoutineRoute: typeof RoutineRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SmartHomeRoute: typeof SmartHomeRoute
  StudyRoute: typeof StudyRoute
  StudyPlannerRoute: typeof StudyPlannerRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-planner': {
      id: '/study-planner'
      path: '/study-planner'
      fullPath: '/study-planner'
      preLoaderRoute: typeof StudyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home': {
      id: '/smart-home'
      path: '/smart-home'
      fullPath: '/smart-home'
      preLoaderRoute: typeof SmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  ChatRoute: ChatRoute,
  FilesRoute: FilesRoute,
  FriendsRoute: FriendsRoute,
  ReaderRoute: ReaderRoute,
  RoutineRoute: RoutineRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SmartHomeRoute: SmartHomeRoute,
  StudyRoute: StudyRoute,
  StudyPlannerRoute: StudyPlannerRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
